### ISSUE TITLE
panic on concurrent map iteration + write from dependency

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/synse-sdk#488]
throwing this here for now for future investigation. in running the OC plugin at one point we got a plugin crash with a big error log, but the interesting bits are:

```
time="2021-01-10T22:34:37.341Z" level=debug msg="[openconfig] constructed device identifier" identifier=0xe-0/0/50efr2.ke2.atl
fatal error: concurrent map iteration and map write

goroutine 6221 [running]:
runtime.throw(0xbee24d, 0x26)
	/usr/local/go/src/runtime/panic.go:774 +0x72 fp=0xc0000cad08 sp=0xc0000cacd8 pc=0x42f4f2
runtime.mapiternext(0xc001f1e840)
	/usr/local/go/src/runtime/map.go:858 +0x579 fp=0xc0000cad90 sp=0xc0000cad08 pc=0x40f499
runtime.mapiterinit(0xade5c0, 0xc000b37710, 0xc001f1e840)
	/usr/local/go/src/runtime/map.go:848 +0x1c3 fp=0xc0000cadb0 sp=0xc0000cad90 pc=0x40ee33
reflect.mapiterinit(0xade5c0, 0xc000b37710, 0xc001b90090)
	/usr/local/go/src/runtime/map.go:1341 +0x54 fp=0xc0000cade0 sp=0xc0000cadb0 pc=0x410464
reflect.(*MapIter).Next(0xc001c60740, 0xc0003dfca8)
	/usr/local/go/src/reflect/value.go:1266 +0x6a fp=0xc0000cae08 sp=0xc0000cade0 pc=0x49463a
internal/fmtsort.Sort(0xade5c0, 0xc0003dfca8, 0x195, 0x1)
	/usr/local/go/src/internal/fmtsort/sort.go:59 +0x146 fp=0xc0000cae88 sp=0xc0000cae08 pc=0x4a6c66
fmt.(*pp).printValue(0xc001c90d00, 0xade5c0, 0xc0003dfca8, 0x195, 0x76, 0x2)
	/usr/local/go/src/fmt/print.go:773 +0xd18 fp=0xc0000cb060 sp=0xc0000cae88 pc=0x4dba48
fmt.(*pp).printValue(0xc001c90d00, 0xbac140, 0xc0003dfc70, 0x199, 0xc000000076, 0x1)
	/usr/local/go/src/fmt/print.go:810 +0x1b45 fp=0xc0000cb238 sp=0xc0000cb060 pc=0x4dc875
fmt.(*pp).printValue(0xc001c90d00, 0xb67a80, 0xc0003dfc70, 0x16, 0x76, 0x0)
	/usr/local/go/src/fmt/print.go:880 +0x194a fp=0xc0000cb410 sp=0xc0000cb238 pc=0x4dc67a
fmt.(*pp).printArg(0xc001c90d00, 0xb67a80, 0xc0003dfc70, 0x76)
	/usr/local/go/src/fmt/print.go:716 +0x2b4 fp=0xc0000cb4a8 sp=0xc0000cb410 pc=0x4da5c4
fmt.(*pp).doPrint(0xc001c90d00, 0xc0000cb5d0, 0x1, 0x1)
	/usr/local/go/src/fmt/print.go:1161 +0xf8 fp=0xc0000cb530 sp=0xc0000cb4a8 pc=0x4df008
fmt.Sprint(0xc0000cb5d0, 0x1, 0x1, 0x14, 0x0)
	/usr/local/go/src/fmt/print.go:249 +0x52 fp=0xc0000cb588 sp=0xc0000cb530 pc=0x4d6f92
github.com/sirupsen/logrus.(*TextFormatter).appendValue(0xc00009f6e0, 0xc00126f050, 0xb67a80, 0xc0003dfc70)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/text_formatter.go:326 +0x165 fp=0xc0000cb5f0 sp=0xc0000cb588 pc=0x520905
github.com/sirupsen/logrus.(*TextFormatter).appendKeyValue(0xc00009f6e0, 0xc00126f050, 0xbd53c7, 0x6, 0xb67a80, 0xc0003dfc70)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/text_formatter.go:320 +0x8f fp=0xc0000cb630 sp=0xc0000cb5f0 pc=0x52076f
github.com/sirupsen/logrus.(*TextFormatter).Format(0xc00009f6e0, 0xc001ef6070, 0x2, 0xc00118d100, 0xc001e64f60, 0xc0000cbc28, 0x47b8a0)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/text_formatter.go:221 +0xa32 fp=0xc0000cbbb8 sp=0xc0000cb630 pc=0x51e7c2
github.com/sirupsen/logrus.(*Entry).write(0xc001ef6070)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:271 +0xa1 fp=0xc0000cbc60 sp=0xc0000cbbb8 pc=0x519071
github.com/sirupsen/logrus.Entry.log(0xc0000a8000, 0xc001b90000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:247 +0x1b2 fp=0xc0000cbce0 sp=0xc0000cbc60 pc=0x518cc2
github.com/sirupsen/logrus.(*Entry).Log(0xc001ef6000, 0x5, 0xc0000cbe68, 0x1, 0x1)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:283 +0xeb fp=0xc0000cbde8 sp=0xc0000cbce0 pc=0x51931b
github.com/sirupsen/logrus.(*Entry).Debug(...)
	/go/pkg/mod/github.com/sirupsen/logrus@v1.7.0/entry.go:292
github.com/vapor-ware/synse-sdk/sdk.(*ReadStream).listen(0xc0012fa780)
	/go/pkg/mod/github.com/vapor-ware/synse-sdk@v0.1.0-alpha.0.20210110152329-2d8d42c478e7/sdk/stream.go:49 +0x48b fp=0xc0000cbfd8 sp=0xc0000cbde8 pc=0xa18b8b
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1357 +0x1 fp=0xc0000cbfe0 sp=0xc0000cbfd8 pc=0x45ece1
created by github.com/vapor-ware/synse-sdk/sdk.(*server).ReadStream
	/go/pkg/mod/github.com/vapor-ware/synse-sdk@v0.1.0-alpha.0.20210110152329-2d8d42c478e7/sdk/server.go:530 +0xa09
```

so looks like the panic is coming from logrus. theres an old PR in the repo that alleges to address this but has not been merged (https://github.com/sirupsen/logrus/pull/667)

there may be a way around this (using WithFields instead of WithField), but I don't know if it'll work - something we need to look at in the future.

**Comment by GuessWhoSamFoo** [comment]
This was resolved in https://github.com/sirupsen/logrus/issues/1217 so the dependency bump to logrus 1.9.0 should include this fix.
